app/config/FrontendConfig.scala
app/controllers/test/TestEndpointController.scala
app/forms/test/FeatureSwitchForm.scala
app/models/test/FeatureSwitch.scala
app/services/HandOffNavigator.scala
app/utils/FeatureSwitch.scala
app/views/test/FeatureSwitch.scala.html
test/controllers/TestEndpointControllerSpec.scala

To enable support, needs a config entry e.g. `microservice.services.comp-reg-frontend.legacyfullurl: https://point-to-the-environment/`
Set the feature using http://localhost:9970/register-your-company/test-only/feature-switch or, if necessary, via config `feature.legacyEnv: 'true'`
Feature **must** be set to the correct value **before** the hand-off model is created on first hand-off.

SCRS-8897 added feature to set environment for handoffs

---

app/views/reg/CancelPaye.scala.html
app/views/reg/Confirmation.scala.html
app/views/reg/Summary.scala.html
conf/application.conf
conf/messages
public/stylesheets/scrs-styling.css

This commit also introduces a couple of tidy up changes too:
• Update list to p.font-large as per GOV.UK examples
http://govuk-elements.herokuapp.com/colour/#examples
https://govuk-prototype-kit.herokuapp.com/docs/examples/confirmation-page
• Update header with class .heading-xlarge and remove inline styles
• Remove superflouos br's and update h2 class
• Add temporary local style overrides with comments
• Remove redundant .column-two-thirds from summary page
• Update messages to match prototype
http://business-reg-prototype.herokuapp.com/1-58-0/incorporation/ConfirmV2
• Update PrinciplePlaceOfBusiness.scala.html to use local error helper to fix styling

Update confirmation page to adopt larger font size for accessibility

---

app/views/reg/ReturningUserView.scala.html

A minor oversight when removing .grid-row and .column-two-thirds parent content wrappers, sporadically reducing the width of content within .content__body

remove column width and parent .grid-row wrapper breaking layout

---

public/stylesheets/scrs-styling.css
public/stylesheets/taas.css

To match CH styling for Get help with this page link that appears below Start now and continue buttons.
I have re-named header.css file to taas.css because this now contains deletable local styles which we can simply remove when Template as a Service (TAAS) come along.

Updating Get help with this page link to match CH

---

app/views/errors/submissionFailed.scala.html
app/views/errors/submissionTimeout.scala.html
app/views/reg/AccountingDates.scala.html
app/views/reg/CancelPaye.scala.html
app/views/reg/CompanyContactDetails.scala.html
app/views/reg/CompletionCapacity.scala.html
app/views/reg/Confirmation.scala.html
app/views/reg/IncompleteRegistration.scala.html
app/views/reg/PrinciplePlaceOfBusiness.scala.html
app/views/reg/Questionnaire.scala.html
app/views/reg/RegistrationUnsuccessful.scala.html
app/views/reg/ReturningUserView.scala.html
app/views/reg/Summary.scala.html
app/views/reg/TestEndpoint.scala.html
app/views/reg/TradingDetailsView.scala.html
app/views/reg/Welcome.scala.html
app/views/test/EMTPPostView.scala.html
app/views/test/FeatureSwitch.scala.html
app/views/verification/createNewAccount.scala.html
test/views/CompanyContactDetailsSpec.scala
test/views/PPOBSpec.scala

Currently we use
- button instead of input type="submit" for Save and continue buttons (http://govuk-elements.herokuapp.com/buttons/#button-text)
- button instead of anchor links for Start now buttons (http://govuk-elements.herokuapp.com/buttons/#button-start-now)
This commit and PR updates this.
I have also removed .btn class because it's doing nothing and isn't required.
There are no visible changes made to show or demo. Only changes in markup.

Update continue and Start now button markup to conform to GOV.UK standards

---

app/views/govuk_wrapper.scala.html
public/stylesheets/scrs-print.css

This includes print styles for template which improve all pages and specific print styles to vastly improve check your answers pages.
Changes include:
- Removing all unnecessary elements for print i.e. back link, phase banner, continue button, change links, sign out links and so on
- improving clarity of service title
- general page tidy up to improve readability of the printed page
[summary-page-before.pdf](https://github.com/hmrc/company-registration-frontend/files/1792926/summary-page-before.pdf)
[summary-page-after.pdf](https://github.com/hmrc/company-registration-frontend/files/1792927/summary-page-after.pdf)

Adding print styles to improve print

---

project/FrontendBuild.scala

play-ui 7.14.0 is transient (as seen in the screenshot)

SCRS-10898 uplifted frontend-boostrap to 8.19.0

---

app/controllers/reg/ReturningUserController.scala
app/controllers/reg/WelcomeController.scala
app/services/EmailVerificationService.scala
app/utils/FeatureSwitch.scala
conf/application.conf
it/itutil/IntegrationSpecBase.scala
it/www/ReturningUserControllerISpec.scala
test/connectors/EmailVerificationConnectorSpec.scala
test/controllers/CompletionCapacityControllerSpec.scala
test/controllers/ReturningUserSpec.scala
test/controllers/SignInOutControllerSpec.scala
test/controllers/SummaryControllerSpec.scala
test/controllers/TestEndpointControllerSpec.scala
test/controllers/WelcomeControllerSpec.scala
test/forms/AccountingDatesFormSpec.scala
test/mocks/SCRSMocks.scala
test/services/EmailVerificationServiceSpec.scala
test/services/HandOffServiceSpec.scala
test/services/TradingDetailsServiceSpec.scala
test/views/SummarySpec.scala
test/views/WelcomeSpec.scala

Under this feature flag:
* /welcome is now permanent redirect to /post-sign-in
* Removal of the email with link to get back to the service
* User is routed to CREFE if they start a new registration

Added signposting feature flag to CRFE

---

app/views/timeout.scala.html
conf/messages
public/stylesheets/header-adjust.css
public/stylesheets/scrs-styling.css

This work updates the service name to 'Set up a limited company and register for Corporation Tax'. This however extends the service name further across the page, thus forcing the 'sign in/out' link to drop below, breaking the layout.
I have added some styles which adjust the layout from a 1/3 | 2/3's split to a 20% | 80% split and set the logo with a minimum width so that doesn't break in the lower screen width range of the tablet breakpoint.

Update service and add styles to adjust header layout

---

app/connectors/CompanyRegistrationConnector.scala
app/controllers/reg/PPOBController.scala
app/models/CompanyDetails.scala
app/models/NewAddress.scala
app/services/PPOBService.scala
app/views/reg/PrinciplePlaceOfBusiness.scala.html
test/connectors/CompanyRegistrationConnectorSpec.scala
test/controllers/PPOBControllerSpec.scala
test/services/PPOBServiceSpec.scala
test/views/PPOBSpec.scala

**New feature** 
* Make a request to the backend to see if the RO can be normalised (valid for DES submission). If it can, display the RO as an option. If it cannot, only display the "Different address" option.
* Send RO addresses to the backend as PPOB if selected.

SCRS-11570: Stop showing RO as option for PPOB if can't normalise

---

project/plugins.sbt
public/javascripts/AccountingDates.js

**Bug fix**
In order to meet the acceptance criteria, the GA event has been amended. This is due to a limitation of GA Pie Charts being unable to group by "value". The new event puts the unique event detail into the "action".
There is also a new "Category" to better describe the scenario now that we have fewer descriptive elements in the GA event.

SCRS-11347 Changed javascript so GA Widget can group by action

---

app/connectors/IncorpInfoConnector.scala
app/controllers/test/SubmissionTriggerController.scala
app/services/internal/CheckIncorporationService.scala
conf/test.routes
project/MicroService.scala
project/plugins.sbt
test/connectors/CompanyRegistrationConnectorSpec.scala
test/connectors/IncorpInfoConnectorSpec.scala
test/controllers/test/SubmissionTriggerControllerSpec.scala
test/mocks/WSHTTPMock.scala
test/services/internal/CheckIncorporationServiceSpec.scala

**New feature**
This commit adds a new endpoint that allows us to incorporate a registration using a transaction ID. It supports Accepted and Rejected through the use of a query string but defaults to **Accepted** if the query string is not provided.

SCRS-11044 Added new test endpoint to incorporate a registration 

---

app/controllers/auth/AuthFunction.scala
project/FrontendBuild.scala
test/utils/AuthFunctionSpec.scala

Redirect to incorrect account page rather than blow up (boom)

Added in redirect to incorrect account type page if auth returns match exception

---

app/views/reg/Questionnaire.scala.html

SCRS-9986 removed the Back link on Questionnaire page

SCRS-9986 removed the Back link on Questionnaire page

---

app/config/frontendAppConfig.scala
app/connectors/BusinessRegistrationConnector.scala
app/connectors/PrepopAddressConnector.scala
it/connectors/PrepopAddressConnectorISpec.scala
it/itutil/WiremockHelper.scala
it/itutil/servicestubs/BusinessRegistrationStub.scala
test/mocks/AccountingServiceMock.scala

- GET to get a list of pre-pop addresses from business registration
- POST to update a single pre-pop address
Could be improved by creating a custom HttpReads a-la VSU, but kept simple for now to avoid scope creep.
* N/A I've executed the acceptance test pack locally to ensure there are no regressions

SAR-4452: Add prepop address connector

---

app/services/TakeoverService.scala
test/mocks/TakeoverServiceMock.scala

SAR-5221 - Add takeover service to call connector

---

app/services/TakeoverService.scala
test/services/TakeoverServiceSpec.scala

Bug fix 
Allowing users to select 'No' then 'Yes' on replacing another business.

SAR-5267 - Fix flow to allow users to change from 'No' to 'Yes'

---

app/views/dashboard/displayRegistrationStatus.scala.html
app/views/templates/layout.scala.html

Also fixes: SAR-10654
**NOTE:** At somepoint, this dashboard requires a much larger refactor. As it uses multiple table instances to render the PAYE Status - rather than having a Table with headers which then contains multiple rows for the different information needed. This is a much bigger change though and outside the scope of this ticket.
**Before this change:**
**After this change:**

[SAR-10653] Refactor so that table is only rendered when not 'NOT_STARTED'

---

app/services/LanguageService.scala
test/models/LanguageSpec.scala
test/services/LanguageServiceSpec.scala

Noddy proxy service almost, but translates the `Lang` instance to a `Language` model via a constructor on the models companion object.

[SAR-10858] Added service to call connector

---

app/controllers/reg/SignInOutController.scala
it/test/www/SignInOutControllerISpec.scala
test/controllers/SignInOutControllerSpec.scala

**Bug fix**
The renew-session call is instigated from Companies House to improve users experience by ensuring that as they transition between pages on the CH incorporation service, the HMRC side of the SCRS service has a refreshed token. If this isn't done then after 15 minutes at CH, the users session at HMRC will have timed out and they would need to log back in to continue the journey.
Without the Cache-Control header, it's ambiguous as to what various caches will do, and there has been a recent example of a response without the header being cached for a short period - which is not something that should happen for this request.
The fix is to include the standard Cache-Control header, which is pulled from the CacheControlFilter provided by the bootstrap library, which will assert that …

DL-14430 Added Cache_Control header to the renew session response
