app/controllers/reg/DashboardController.scala
app/controllers/test/TestEndpointController.scala
app/views/reg/Dashboard.scala.html
conf/application.conf
test/controllers/DashboardControllerSpec.scala
test/views/DashboardSpec.scala

Good to merge. The urls have been provided to the app configs for prod, qa and staging.

SCRS-8408 Dashboard sign-in url no longer hard coded

---

conf/app.routes

Go ahead given to remove these

Removed old urls apart from /welcome

---

app/views/dashboard/CancelPaye.scala.html
app/views/dashboard/CancelVat.scala.html
app/views/dashboard/Dashboard.scala.html
app/views/endpoints/IncorporationStatusEndpoint.scala.html
app/views/error_template_restart.scala.html
app/views/errors/deskproSubmitted.scala.html
app/views/errors/submissionFailed.scala.html
app/views/errors/submissionTimeout.scala.html
app/views/feedback.scala.html
app/views/helpers/InlineDateInput.scala.html
app/views/reg/AccountingDates.scala.html
app/views/reg/CompanyContactDetails.scala.html
app/views/reg/CompletionCapacity.scala.html
app/views/reg/Confirmation.scala.html
app/views/reg/IncompleteRegistration.scala.html
app/views/reg/LimitReached.scala.html
app/views/reg/PrinciplePlaceOfBusiness.scala.html
app/views/reg/RegistrationUnsuccessful.scala.html
app/views/reg/ReturningUserView.scala.html
app/views/reg/Summary.scala.html
app/views/reg/TestEndpoint.scala.html
app/views/reg/TradingDetailsView.scala.html
app/views/reg/Welcome.scala.html
app/views/timeout.scala.html
conf/messages
it/www/DashboardControllerISpec.scala
test/controllers/DashboardControllerSpec.scala
test/views/DashboardSpec.scala

DAC report highlighted the following fixes to improve accessibility:
- Check, update and add descriptive legends to all fieldsets
- Update 'Contact number' inputs to use type="tel"
- Ensure all grouped form elements are contained within a fieldset
As part of addressing these fails I have also:
- refactored conf/messages
- updated class .visuallyhidden to .visually-hidden 
- other general tidying up and refactoring as I spot when going through files worked on
NOTE: there are not visible changes to show with screenshots.

Fixes in response to fails in DAC report

---

app/views/dashboard/Dashboard.scala.html
app/views/dashboard/vatDashboard.scala.html
conf/application.conf
public/stylesheets/dashboard.css
public/stylesheets/scrs-styling.css

This commit and PR is more complexed than simply making the dashboard fonts consistent.
Work done:
- Remove all the inline styles managing table column widths and font sizes
- Add in new CSS to manage the necessary styles
- Update headings to use correct heirarchy structure
- Tidy table markup - remove superflouos multiple <thead> and <tbody>
- Remove unused class .list
Note: there are no visual changes to show.

Make dashboard fonts consistent

---

app/views/dashboard/Dashboard.scala.html
test/views/DashboardSpec.scala

* Amend dashboard to treat 06, 07, 08, 09, 10 ackref statuses as rejected cases

SCRS-10561

---

app/controllers/reg/PPOBController.scala
test/controllers/PPOBControllerSpec.scala

SCRS-11570 Resolved RO address appearing after not selecting PPOB
**Fix**
For a bad request showing an invalid RO address.

SCRS-11570 Resolved RO address appearing after not selecting PPOB

---

project/FrontendBuild.scala
project/build.properties

*SCRS-11380*
**Dependency Uplift**
Uplifted minor dependencies that require no code change. Raised SCRS-11694 to deal with the non-trivial mongo change

SCRS-11380 Uplifted minor dependencies

---

app/views/reg/Questionnaire.scala.html
conf/messages
project/FrontendBuild.scala
project/plugins.sbt

** New feature** (delete as appropriate)
Content change on questionnaire to make it GDPR compliant.

SCRS-11702 Update questionnaire to be GDPR compliant

---

app/views/reg/AccountingDates.scala.html
public/javascripts/AccountingDates.js

**New feature**
Added a GA event on the accounting dates page. This only records the ID of the radio button selection.

Added GA event for accounting dates page

---

app/views/reg/Confirmation.scala.html

**Bug fix** (delete as appropriate)
removed duplication content from confirmation page

[SCRS-11572] fixed confirmation duplicate

---

app/config/frontendGlobal.scala
project/MicroService.scala
project/plugins.sbt

SCRS-11994 - updated for new build server

SCRS-11994 - updated for new build server, removed redundant code

---

app/connectors/ServiceConnector.scala

Simple fix, no tests have changed, just to clear up junk in logs, user was never affected

SCRS-12114 - changed cancelReg to stop using match against http response causing unapply error because json body is empty

---

app/services/TimeService.scala
project/FrontendBuild.scala
test/services/TimeServiceSpec.scala

Upcoming bank holidays for 2018 and 2019 added to TimeService.scala
* [x ] I've added my code using logical, atomic commits, squashing as appropriate - including the Jira issue number in the commit message

SCRS-12196 Bank Holidays for 2018 and 2019 added

---

app/views/reg/TradingDetailsView.scala.html
conf/app.routes
conf/messages
it/www/AccountingDetailsISpec.scala
project/FrontendBuild.scala
project/plugins.sbt
public/javascripts/scrsScripts.js
test/controllers/AccountingDatesControllerSpec.scala
test/controllers/handoff/BusinessActivitiesControllerSpec.scala

SCRS-9699 CT61 content and URL change. Also plugin updates

SCRS-9699 CT61 content and URL change. Also plugin updates

---

app/controllers/test/TestEndpointController.scala
conf/app.routes
test/services/HandOffServiceSpec.scala

SCRS-12244 - removing trading-details url

SCRS-12244 - removing trading-details url

---

app/views/reg/Summary.scala.html
conf/messages
it/www/SummaryControllerISpec.scala
test/views/SummarySpec.scala

SCRS-11695 - Contact Details summary changes

SCRS-11695 - Contact Details summary changes

---

app/controllers/auth/AuthFunction.scala
app/controllers/reg/ReturningUserController.scala
app/views/reg/ReturningUserView.scala.html
conf/messages
public/javascripts/scrsScripts.js
test/controllers/ReturningUserSpec.scala
test/utils/AuthFunctionSpec.scala

SCRS-11862 Single user per company

SCRS-11862 Single user per company

---

app/models/handoff/PSCHandOff.scala
it/www/GroupsControllerISpec.scala

Added in default flag of false for payload on ho31

fix for hand off to have default boolean value in payload

---

app/views/dashboard/Dashboard.scala.html
app/views/dashboard/displayRegistrationActions.scala.html
app/views/dashboard/vatDashboard.scala.html
app/views/feedback.scala.html
app/views/feedback_thankyou.scala.html
app/views/govuk_wrapper.scala.html
app/views/reg/AccountingDates.scala.html
app/views/reg/Summary.scala.html
app/views/reg/TradingDetailsView.scala.html
app/views/test/EMTPPostView.scala.html
conf/application.conf
conf/messages
project/FrontendBuild.scala
public/stylesheets/dashboard.css
public/stylesheets/styling-fix.css
public/stylesheets/timeout-dialog1.css

SCRS-12001 - assets uplift to 3.7.0 with fixes

SCRS-12001 - assets uplift to 3.7.0 with fixes

---

app/views/errors/submissionTimeout.scala.html

Quick spacing fix to /submission-failure page

Quick spacing fix to /submission-failure page

---

conf/app.routes

fixed routes to not point to post sign in

SCRS-12373-fixed routes

---

conf/messages

SCRS-12373-content-fix.  Update to companies-house-email-confirm page

SCRS-12373-content-fix.  Update to companies-house-email-confirm page

---

it/www/GroupControllerISpec.scala

removed drop assertion, changed to count mustBe 0

Changed drop func

---

app/config/filters/SessionIdFilter.scala

fixed filters

---

app/config/frontendWiring.scala
app/controllers/reg/CompanyContactDetailsController.scala
app/services/CompanyContactDetailsService.scala
it/itutil/WiremockHelper.scala
it/repositories/NavModelRepositorySpec.scala
it/www/BasicCompanyDetailsControllerISpec.scala
it/www/CompanyContactDetailsControllerISpec.scala
it/www/CompletionCapacityControllerISpec.scala
it/www/DashboardControllerISpec.scala
it/www/GroupControllerISpec.scala
it/www/HandOffsISpec.scala
it/www/RegistrationConfirmationISpec.scala
it/www/RegistrationEmailConfirmationISpec.scala
it/www/RegistrationEmailControllerISpec.scala
it/www/ReturningUserControllerISpec.scala
it/www/VerifyYourEmailISpec.scala
project/FrontendBuild.scala
project/MicroService.scala
project/plugins.sbt
test/controllers/CompanyContactDetailsControllerSpec.scala
test/controllers/auth/AuthFunctionSpec.scala
test/fixtures/AddressLookupFixture.scala
test/fixtures/CompanyContactDetailsFixture.scala
test/mocks/CompanyContactDetailsServiceMock.scala
test/services/CompanyContactDetailsServiceSpec.scala
test/views/CompanyContactDetailsSpec.scala

SCRS-12792 - prepop Contact Email from saved verified email

SCRS-12792 - prepop Contact Email from saved verified email

---

app/config/frontendGlobal.scala
conf/logback.xml
project/FrontendBuild.scala

Wrong filters being used and Logback xml amendment

Fix to filters and logback xml

---

app/connectors/CompanyRegistrationConnector.scala
app/models/handoff/CompanyNameHandOffModel.scala
app/services/HandBackService.scala
it/fixtures/HandOffFixtures.scala
it/itutil/WiremockHelper.scala
it/www/CorporationTaxDetailsControllerISpec.scala
project/plugins.sbt
test/connectors/CompanyRegistrationConnectorSpec.scala
test/controllers/handoff/CorporationTaxDetailsControllerSpec.scala
test/fixtures/CompanyDetailsFixture.scala
test/fixtures/PayloadFixture.scala
test/models/handoff/CompanyNameHOIncomingSpec.scala
test/services/HandBackServiceSpec.scala

SCRS-12861 Handle TXID and call new CR endpoint to save TXID after HO2## Checklist

SCRS-12861 Handle TXID and call new CR endpoint to save TXID after HO2

---

app/services/DashboardService.scala
project/FrontendBuild.scala
project/plugins.sbt
test/services/DashboardServiceSpec.scala

SCRS-12884 - updated PAYE thresholds for new tax year on summary page

SCRS-12884 - updated PAYE thresholds for new tax year on summary page

---

app/connectors/EmailVerificationConnector.scala
conf/application.conf
it/www/SignInOutControllerISpec.scala
test/connectors/EmailVerificationConnectorSpec.scala

SCRS-12908 amended email call to be a POST

SCRS-12908 amended email call to be a POST

---

app/connectors/EmailVerificationConnector.scala
it/www/SignInOutControllerISpec.scala

SCRS-12908 - email url fix

---

app/audit/events/EmailVerifiedEvent.scala
app/controllers/auth/AuthFunction.scala
app/controllers/reg/CompanyContactDetailsController.scala
app/controllers/reg/RegistrationEmailConfirmationController.scala
app/controllers/reg/RegistrationEmailController.scala
app/controllers/verification/EmailVerificationController.scala
app/services/EmailVerificationService.scala
app/utils/FeatureSwitch.scala
it/itutil/IntegrationSpecBase.scala
it/www/CompanyContactDetailsControllerISpec.scala
it/www/RegistrationEmailConfirmationISpec.scala
it/www/RegistrationEmailControllerISpec.scala
project/FrontendBuild.scala
test/controllers/RegistrationEmailConfirmationControllerSpec.scala
test/controllers/RegistrationEmailControllerSpec.scala
test/controllers/auth/AuthFunctionSpec.scala
test/controllers/handoff/RegistrationConfirmationControllerSpec.scala
test/controllers/verification/EmailVerificationControllerSpec.scala
test/services/EmailVerificationServiceSpec.scala

SCRS-12818 removed scp feature switch, added email audit event on save IF verify = true

---

project/FrontendBuild.scala
project/plugins.sbt

SAR-4074 - Update dependencies

---

conf/application.conf

Handling SSLEngine closed already exceptions

Handling SSLEngine closed already exceptions

---

app/controllers/test/TestEndpointController.scala
app/forms/test/FeatureSwitchForm.scala
app/models/test/FeatureSwitch.scala
app/utils/FeatureSwitch.scala
app/views/test/FeatureSwitch.scala.html
project/FrontendBuild.scala
test/controllers/TestEndpointControllerSpec.scala

**New feature**
Added a takeovers feature switch to the list of current feature switches,
Updated the feature switches page to include the new feature switch for easy toggling
Updated dependencies of anything which did not cause tests to fail.

SAR-4412 - Updated feature switches to include a takeovers feature switch

---

app/config/frontendAppConfig.scala
app/connectors/TakeoverConnector.scala
app/models/TakeoverDetails.scala
conf/logback-test.xml
it/connectors/TakeoverConnectorISpec.scala
it/itutil/WiremockHelper.scala
it/itutil/servicestubs/TakeoverStub.scala
project/MicroService.scala

**New feature** (delete as appropriate)
Add connector to takeover API

SAR-4418 - Add connector to takeover API

---

it/www/AccountingDetailsISpec.scala

SAR-5148 Update ISpec
Update the ISpec for 2020

SAR-5148 Update ISpec for 2020

---

app/utils/JWE.scala

SAR-5111 update errors to produce stack trace
Update the kibana error logging to include the StackTrace

SAR-5111 update errors to produce stack trace

---

README.md

SAR-5155 - General housekeeping. Update the readme

SAR-5155 Update the readme

---

app/repositories/TTLIndexing.scala
project/FrontendBuild.scala

SAR-5222: Updated play-reactivemongo to simple-reactivemongo

---

app/controllers/takeovers/ReplacingAnotherBusinessController.scala
app/forms/takeovers/ReplacingAnotherBusinessForm.scala
app/models/TakeoverDetails.scala
app/services/TakeoverService.scala
app/views/takeovers/ReplacingAnotherBusiness.scala.html
conf/app.routes
conf/messages
it/connectors/TakeoverConnectorISpec.scala
it/itutil/IntegrationSpecBase.scala
it/www/ReplacingAnotherBusinessControllerISpec.scala
test/controllers/takeovers/ReplacingAnotherBusinessControllerSpec.scala
test/mocks/SCRSMocks.scala
test/mocks/TakeoverConnectorMock.scala
test/mocks/TakeoverServiceMock.scala
test/services/TakeoverServiceSpec.scala
test/views/takeovers/ReplacingAnotherBusinessViewSpec.scala

SAR-5193 - Add replacing another business page
New feature
Adding new replacing another business page

SAR-5193 - Add replacing another business page

---

app/controllers/reg/CompanyContactDetailsController.scala
test/controllers/CompanyContactDetailsControllerSpec.scala
test/controllers/takeovers/ReplacingAnotherBusinessControllerSpec.scala
test/mocks/SCRSMocks.scala
test/views/CompanyContactDetailsSpec.scala

SAR-5251 - Route into takeover controller from contact details

---

app/controllers/takeovers/OtherBusinessNameController.scala
app/controllers/takeovers/ReplacingAnotherBusinessController.scala
app/forms/takeovers/OtherBusinessNameForm.scala
app/services/TakeoverService.scala
app/utils/SCRSValidators.scala
app/views/takeovers/OtherBusinessName.scala.html
conf/app.routes
conf/messages
it/www/OtherBusinessNameControllerISpec.scala
test/controllers/takeovers/OtherBusinessNameControllerSpec.scala
test/controllers/takeovers/ReplacingAnotherBusinessControllerSpec.scala
test/mocks/TakeoverServiceMock.scala
test/views/takeovers/OtherBusinessNameViewSpec.scala

* [] I've executed the acceptance test pack locally to ensure there are no regressions
* [] I've run a dependency check to ensure all dependencies are up to date

SAR-5199 Added other business name page and controller

---

it/www/RegistrationEmailConfirmationISpec.scala

Updated an audit check to be more specific to avoid odd failures

---

app/controllers/reg/SummaryController.scala
app/views/reg/Summary.scala.html
conf/messages
it/www/SummaryControllerISpec.scala
test/controllers/SummaryControllerSpec.scala
test/views/SummarySpec.scala

SAR-5195: Add replacing another business to summary page

---

conf/messages
test/views/SummarySpec.scala

SAR-5195: Typos on CYA for Replacing another business

---

app/views/reg/Summary.scala.html
conf/messages
test/views/SummarySpec.scala

SAR-5201: Updated Summary to include Other Business Name

---

test/services/TakeoverServiceSpec.scala

SAR-5268 added update business name tests for TakeoverService

---

project/FrontendBuild.scala
project/plugins.sbt

SAR-5322: Updated dependencies

---

app/views/helpers/inputRadioGroupAddresses.scala.html
conf/messages

SAR-5339 created an input radio helper for addresses

---

conf/application.conf

SAR-5320 - Disable Welsh as it is not currently supported

SAR-5320 - Disable Welsh

---

app/connectors/CompanyRegistrationConnector.scala
app/connectors/PrepopAddressConnector.scala
app/controllers/groups/GroupAddressController.scala
app/models/NewAddress.scala
app/services/AddressPrepopulationService.scala
app/services/GroupService.scala
it/connectors/PrepopAddressConnectorISpec.scala
it/itutil/servicestubs/BusinessRegistrationStub.scala
project/MicroService.scala
test/fixtures/AddressFixture.scala
test/mocks/CompanyRegistrationConnectorMock.scala
test/mocks/PrepopAddressConnectorMock.scala
test/mocks/SCRSMocks.scala
test/services/AddressPrepopulationServiceSpec.scala
test/services/GroupServiceSpec.scala

**New feature**
* [] I've executed the acceptance test pack locally to ensure there are no regressions

SAR-5344 - Add new service to retrieve addresses

---

app/controllers/takeovers/OtherBusinessAddressController.scala
app/controllers/takeovers/OtherBusinessNameController.scala
app/forms/takeovers/OtherBusinessAddressForm.scala
app/services/TakeoverService.scala
app/views/takeovers/OtherBusinessAddress.scala.html
conf/app.routes
conf/messages
it/itutil/WiremockHelper.scala
it/www/takeovers/OtherBusinessAddressControllerISpec.scala
it/www/takeovers/OtherBusinessNameControllerISpec.scala
it/www/takeovers/ReplacingAnotherBusinessControllerISpec.scala
test/controllers/takeovers/OtherBusinessAddressControllerSpec.scala
test/controllers/takeovers/OtherBusinessNameControllerSpec.scala
test/mocks/AddressPrepopulationServiceMock.scala
test/mocks/TakeoverServiceMock.scala
test/services/TakeoverServiceSpec.scala
test/views/takeovers/OtherBusinessAddressViewSpec.scala

SAR-5330 Added Takeovers address page and controller

---

app/models/TakeoverDetails.scala
app/views/reg/Summary.scala.html
conf/messages
test/views/SummarySpec.scala

SAR-5337 Updated summary screen for Takeover address

SAR-5337 Updated summary screen for Takeover address

---

app/controllers/takeovers/OtherBusinessAddressController.scala
app/forms/takeovers/OtherBusinessAddressForm.scala
app/utils/StringUtil.scala
app/views/takeovers/OtherBusinessAddress.scala.html
conf/messages
test/controllers/takeovers/OtherBusinessAddressControllerSpec.scala
test/views/takeovers/OtherBusinessAddressViewSpec.scala

SAR-5353 updated validation to fail in invalid form inputs, made error message dynamic

---

project/plugins.sbt

removed sbt-bobby plugin

---

app/views/reg/Summary.scala.html
conf/messages
test/views/SummarySpec.scala

SAR-5239 - CYA for who agreed the takeover

SAR-5239 - CYA for who agreed the takeover

---

app/views/reg/Summary.scala.html
conf/messages
test/views/SummarySpec.scala

SAR-5370: Update CYA change link hidden text

---

app/views/reg/Summary.scala.html
conf/messages
test/views/SummarySpec.scala

SAR-5361: Updated Summary view and tests to include Previous Owners Home Address page

---

app/controllers/reg/PPOBController.scala
app/models/AlfJourneyConfig.scala
app/services/AddressLookupConfigBuilderService.scala
app/views/timeout_script.scala.html
conf/app.routes
it/www/PPOBControllerISpec.scala
it/www/takeovers/OtherBusinessAddressControllerISpec.scala
it/www/takeovers/PreviousOwnersAddressControllerISpec.scala
test/controllers/PPOBControllerSpec.scala
test/services/AddressLookupConfigBuilderServiceSpec.scala
test/services/AddressLookupFrontendServiceSpec.scala

SAR-5417 updated PPOB to use generic ALF implementation

---

app/controllers/groups/GroupAddressController.scala
app/services/AddressLookupFrontendService.scala
conf/app.routes
conf/messages
it/www/GroupControllerISpec.scala
test/controllers/GroupAddressControllerSpec.scala
test/mocks/AddressLookupFrontendServiceMock.scala
test/services/AddressLookupFrontendServiceSpec.scala

SAR-5418 updated groups to use generic alf implementation and removed old alf code

---

app/services/DashboardService.scala
app/views/timeout_script.scala.html
test/services/DashboardServiceSpec.scala

SAR-5410 - Amended PAYE threshold values for 6 APR 2020

---

test/services/DashboardServiceSpec.scala

SAR-5455 Fix to failing tests because we have entered a new tax year

---

app/views/govuk_wrapper.scala.html

SAR-5464: Remove reference to timeout-dialog.js in gov-uk wrapper

---

app/controllers/groups/GroupAddressController.scala
app/controllers/reg/PPOBController.scala
app/models/AlfJourneyConfig.scala
app/services/AddressLookupConfigBuilderService.scala
app/services/AddressLookupFrontendService.scala
conf/app.routes
conf/messages
it/www/GroupControllerISpec.scala
it/www/PPOBControllerISpec.scala
it/www/takeovers/OtherBusinessAddressControllerISpec.scala
it/www/takeovers/PreviousOwnersAddressControllerISpec.scala
test/controllers/GroupAddressControllerSpec.scala
test/controllers/PPOBControllerSpec.scala
test/mocks/AddressLookupFrontendServiceMock.scala
test/services/AddressLookupConfigBuilderServiceSpec.scala
test/services/AddressLookupFrontendServiceSpec.scala

SAR-5167 Updated all alf calls to match takeovers approach

---

app/utils/SCRSValidators.scala
conf/messages
test/controllers/takeovers/OtherBusinessNameControllerSpec.scala

SAR-5411 updated other business name validation and error message

---

app/controllers/reg/PPOBController.scala
app/services/PPOBService.scala
app/views/reg/PrinciplePlaceOfBusiness.scala.html
project/FrontendBuild.scala
test/services/PPOBServiceSpec.scala
test/views/PPOBSpec.scala

SAR-5499 Fix for duplicate addresses for PPOB

SAR-5499 Fix for duplicate addresses for PPOB

---

app/views/groups/GroupUtrView.scala.html
test/views/GroupReliefSpec.scala
test/views/GroupUtrSpec.scala

SAR-5501: Added parentCompanyName to GroupUtr view

---

app/models/NewAddress.scala
test/models/NewAddressSpec.scala

SAR-5564 - Fix for re-entering groups flow

---

app/views/help/accessibility_statement.scala.html
conf/messages
test/views/help/AccessibilityStatementSpec.scala

SAR-5532 - Create accessibility statement view

---

app/config/frontendAppConfig.scala
app/controllers/AccessibilityStatementController.scala
app/views/govuk_wrapper.scala.html
conf/app.routes
conf/application.conf
test/controllers/AccessibilityStatementControllerSpec.scala

SAR-5533 created an accessibility statement controller

---

app/config/Module.scala
app/controllers/groups/GroupAddressController.scala
app/controllers/groups/GroupNameController.scala
app/controllers/groups/GroupReliefController.scala
app/controllers/groups/GroupUtrController.scala
app/controllers/handoff/GroupController.scala
app/services/GroupService.scala
app/services/GroupServiceDeprecated.scala
test/controllers/GroupAddressControllerSpec.scala
test/controllers/GroupNameControllerSpec.scala
test/controllers/GroupReliefControllerSpec.scala
test/controllers/GroupUtrControllerSpec.scala
test/controllers/handoff/GroupControllerSpec.scala
test/mocks/SCRSMocks.scala
test/services/GroupServiceDeprecatedSpec.scala
test/views/GroupReliefSpec.scala
test/views/GroupUtrSpec.scala

SAR-5546 refactored group utr code

---

app/config/Module.scala
app/controllers/groups/GroupAddressController.scala
app/services/GroupService.scala
test/controllers/GroupAddressControllerSpec.scala
test/services/GroupServiceSpec.scala

SAR-5547 refactored group address controller

---

app/config/Module.scala
app/controllers/groups/GroupReliefController.scala
app/services/GroupService.scala
test/controllers/GroupReliefControllerSpec.scala
test/services/GroupServiceSpec.scala
test/views/GroupReliefSpec.scala

SAR-5550 Refactored GroupReliefController and related tests

---

app/connectors/AddressLookupConnector.scala
app/models/AlfJourneyConfig.scala
app/services/AddressLookupConfigBuilderService.scala
app/services/AddressLookupFrontendService.scala
it/itutil/servicestubs/ALFStub.scala
it/www/GroupControllerISpec.scala
it/www/PPOBControllerISpec.scala
it/www/takeovers/OtherBusinessAddressControllerISpec.scala
it/www/takeovers/PreviousOwnersAddressControllerISpec.scala
test/connectors/AddressLookupConnectorSpec.scala
test/mocks/AddressLookupConfigBuilderServiceMock.scala
test/services/AddressLookupConfigBuilderServiceSpec.scala
test/services/AddressLookupFrontendServiceSpec.scala

Co-authored-by: Nathan Farnell <63645158+NathanFarnell@users.noreply.github.com>
Co-authored-by: Rob Hawkes <17453872+kabuumu@users.noreply.github.com>

Moving to V2 API of Address Lookup

---

app/config/Module.scala
app/controllers/groups/GroupNameController.scala
app/services/GroupService.scala
test/controllers/GroupNameControllerSpec.scala
test/services/GroupServiceSpec.scala

SAR-5548 GroupNameController refactor

---

README.md

SAR-5623 - Updated readme with new run instructions

---

app/controllers/handoff/GroupController.scala
app/utils/FeatureSwitch.scala
test/controllers/handoff/GroupControllerSpec.scala

SAR-5638 Removal of pscHandOff feature switch

---

project/FrontendBuild.scala

* [] I've run a dependency check to ensure all dependencies are up to date

SAR-5854 Update simple reactive mongo

---

app/config/frontendAppConfig.scala
app/models/AlfJourneyConfig.scala
app/services/AddressLookupConfigBuilderService.scala
app/services/AddressLookupFrontendService.scala
it/www/PPOBControllerISpec.scala
it/www/takeovers/OtherBusinessAddressControllerISpec.scala
it/www/takeovers/PreviousOwnersAddressControllerISpec.scala
test/services/AddressLookupConfigBuilderServiceSpec.scala
test/services/AddressLookupFrontendServiceSpec.scala

Please double check the AT's pass - still having issues running them on my machine

Adding AccessibilityStatementURl to ALF pages

---

app/views/groups/GroupNameView.scala.html

SAR-5972 - Added error summary to owning-company-name page

---

app/views/dashboard/CancelPaye.scala.html
app/views/dashboard/CancelVat.scala.html
app/views/groups/GroupAddressView.scala.html
app/views/groups/GroupNameView.scala.html
app/views/groups/GroupReliefView.scala.html
app/views/groups/GroupUtrView.scala.html
app/views/helpers/RadioGroupHidden.scala.html
app/views/helpers/inputRadioGroup.scala.html
app/views/helpers/inputRadioGroupAddresses.scala.html
app/views/helpers/inputRadioGroupHidden.scala.html
app/views/helpers/inputRadioGroupSCRS.scala.html
app/views/reg/AccountingDates.scala.html
app/views/reg/CompanyContactDetails.scala.html
app/views/reg/CompletionCapacity.scala.html
app/views/reg/ConfirmRegistrationEmail.scala.html
app/views/reg/PrinciplePlaceOfBusiness.scala.html
app/views/reg/Questionnaire.scala.html
app/views/reg/RegistrationEmail.scala.html
app/views/reg/ReturningUserView.scala.html
app/views/reg/TradingDetailsView.scala.html
app/views/takeovers/HomeAddress.scala.html
app/views/takeovers/OtherBusinessAddress.scala.html
app/views/takeovers/ReplacingAnotherBusiness.scala.html
app/views/test/FeatureSwitch.scala.html
test/views/GroupReliefSpec.scala
test/views/GroupUtrSpec.scala
test/views/PPOBSpec.scala

SAR_6002 Add H1 within fieldset legend option to all radio helpers

---

app/config/frontendAppConfig.scala
app/views/govuk_wrapper.scala.html
conf/messages

CR-FE] Update footer links in govuk-wrapper

---

conf/application.conf

SAR-6308 - Added max-uri-length into app.conf

---

app/controllers/auth/AuthenticatedController.scala
app/controllers/handoff/BusinessActivitiesController.scala

Play26 auth logging investigation

---

app/controllers/auth/AuthenticatedController.scala

SAR-6397b - Adding more logging for looping issue

---

app/views/dashboard/vatDashboard.scala.html
test/views/DashboardSpec.scala

SAR-6663 - update VAT url on dashboard

---

app/controllers/handoff/CorporationTaxDetailsController.scala

SAR-6397-NOV19 added auth logging onto HO2

---

app/config/frontendAppConfig.scala
conf/application.conf
it/www/SignInOutControllerISpec.scala
it/www/VerifyYourEmailISpec.scala
test/controllers/RegistrationEmailConfirmationControllerSpec.scala
test/controllers/SignInOutControllerSpec.scala
test/controllers/auth/AuthFunctionSpec.scala
test/controllers/verification/EmailVerificationControllerSpec.scala
test/fixtures/LoginFixture.scala

SAR-6737: Removes uses of CA frontend

---

app/controllers/auth/AuthenticatedController.scala
test/controllers/RegistrationEmailConfirmationControllerSpec.scala
test/controllers/auth/AuthFunctionSpec.scala
test/fixtures/LoginFixture.scala

SAR-6742: Update continue_url in Bas gateway url

---

conf/application.conf

SAR-6397-NOV - Added CORS filter for looping issue

---

conf/application.conf

SAR-6397-10DEC - update setting for loopers after advice from auth team

---

app/views/govuk_wrapper.scala.html
conf/application.conf
project/FrontendBuild.scala

SAR-6798: Integrate with Tracking Consent Frontend

---

app/views/govuk_wrapper.scala.html
conf/application.conf

FixCSP: Added Optimizely to CSP

---

conf/application.conf

Reverts hmrc/company-registration-frontend#263

Revert "Fix for CORS issue"

---

conf/application.conf

SAR-7266 - added google-analytics to CSP

---

app/controllers/takeovers/TakeoverInformationNeededController.scala
app/views/errors/takeoverInformationNeeded.scala.html
conf/app.routes
conf/messages
it/www/takeovers/TakeoverInformationNeededControllerISpec.scala
test/views/takeovers/TakeoverInformationNeededViewSpec.scala

Added new view and controller for takeover error page to be called fom cya

SAR-7261 new view and controller for takeover error

---

app/controllers/takeovers/TakeoverInformationNeededController.scala
app/views/errors/takeoverInformationNeeded.scala.html
it/www/takeovers/TakeoverInformationNeededControllerISpec.scala
test/views/takeovers/TakeoverInformationNeededViewSpec.scala

new views form action was set to submit causing errors upon redirect. PR to change it to show fixing the problem also optimising imports from the previous subtask

SAR-7276 form action changed to show

---

app/views/policies.scala.html
test/views/PolicySpec.scala

SAR-7356 Update CH Cookie policy link

---

app/views/help/accessibility_statement.scala.html
conf/messages
test/views/help/AccessibilityStatementSpec.scala

SAR-8784 Update accessibility statement

---

project/AppDependencies.scala
project/build.properties
project/plugins.sbt

SAR-10240: Update dependencies

---

app/models/handoff/HandOffNavModel.scala
app/repositories/NavModelRepository.scala
test/models/handoff/HandOffNavModelSpec.scala

This way, the Repo can have a domainFormat that is based on a case class which represents the data held at rest. The methods on the repo remain unchanged, so they still return the sub-model that's nested within the MongoModel.
This also includes a fix for the lastUpdated field, as when this was switched from Joda.time it lost the Mongo formatters for the date. So this is now added.
To try and prevent this issue from happening going forward I've added tests for the Json read/writes for the Mongo format so that this will trap any regressions in future.

[SAR-10560] Refactor to introduce a new model to represent the Mongo data at rest

---

app/views/groups/GroupNameView.scala.html
app/views/reg/CompletionCapacity.scala.html
app/views/takeovers/OtherBusinessAddress.scala.html
it/www/GroupControllerISpec.scala
it/www/takeovers/OtherBusinessAddressControllerISpec.scala

**Note:**
- this should also fix SAR-10657
- requires AT change here: https://github.com/hmrc/company-registration-acceptance-tests/pull/57

[SAR-10656] Refactor so that the IDs don't contain whitespace

---

app/config/AppConfig.scala
conf/application.conf

https://github.com/hmrc/app-config-base/pull/7699

Add config for accessibility statement config

---

app/assets/stylesheets/application.scss
app/views/components/span.scala.html
app/views/reg/RegistrationEmail.scala.html

[SAR-10802] Add CSS to wrap on overflow for email address

---

app/config/AppConfig.scala
app/controllers/LanguageSwitchController.scala
app/controllers/auth/AuthenticatedController.scala
app/controllers/handoff/BasicCompanyDetailsController.scala
app/controllers/handoff/BusinessActivitiesController.scala
app/controllers/handoff/CorporationTaxDetailsController.scala
app/controllers/handoff/CorporationTaxSummaryController.scala
app/controllers/handoff/GroupController.scala
app/controllers/handoff/HandOffUtils.scala
app/controllers/handoff/IncorporationSummaryController.scala
app/controllers/handoff/RegistrationConfirmationController.scala
app/utils/FeatureSwitch.scala
app/utils/SessionRegistration.scala
conf/app.routes
conf/application.conf
conf/logback.xml
test/controllers/LanguageSwitchControllerSpec.scala
test/controllers/handoff/BasicCompanyDetailsControllerSpec.scala
test/controllers/handoff/BusinessActivitiesControllerSpec.scala
test/controllers/handoff/CorporationTaxDetailsControllerSpec.scala
test/controllers/handoff/CorporationTaxSummaryControllerSpec.scala
test/controllers/handoff/GroupControllerSpec.scala
test/controllers/handoff/IncorporationSummaryControllerSpec.scala
test/controllers/handoff/RegistrationConfirmationControllerSpec.scala
test/mocks/SCRSMocks.scala
test/utils/FeatureSwitchSpec.scala

**Note:** also includes a small refactor to allow feature toggles to be enabled via app-config
https://user-images.githubusercontent.com/16954819/200812095-df394b18-99cd-4222-8fc4-20f0f99e19c1.mp4

[SAR-10859] Call the service to update BE language held on toggle switch and COHO handback

---

app/controllers/reg/SummaryController.scala
test/controllers/SummaryControllerSpec.scala

DL-10037 - fixed submission error

---

app/views/reg/IncompleteRegistration.scala.html
app/views/templates/layout.scala.html
project/AppDependencies.scala
project/plugins.sbt

[DL-13094] play-frontend-hmrc upgrade

---

app/models/JavaTimeUtils/BankHoliday.scala
app/models/JavaTimeUtils/DateTimeUtils.scala
app/services/TimeService.scala
app/utils/SCRSValidators.scala
test/controllers/TestEndpointControllerSpec.scala
test/fixtures/AccountingDatesFixture.scala
test/forms/AccountingDatesFormSpec.scala
test/services/CommonServiceSpec.scala
test/services/ThresholdServiceSpec.scala
test/services/TimeServiceSpec.scala
test/utils/SCRSValidatorsSpec.scala

[DL-16258] Fetch bank holidays from official gov service rather than hardcoded

---

app/models/JavaTimeUtils/BankHoliday.scala
app/models/JavaTimeUtils/DateTimeUtils.scala
app/services/TimeService.scala
app/utils/SCRSValidators.scala
test/controllers/TestEndpointControllerSpec.scala
test/fixtures/AccountingDatesFixture.scala
test/forms/AccountingDatesFormSpec.scala
test/services/CommonServiceSpec.scala
test/services/ThresholdServiceSpec.scala
test/services/TimeServiceSpec.scala
test/utils/SCRSValidatorsSpec.scala

Reverts hmrc/company-registration-frontend#358

Revert "[DL-16258] Fetch bank holidays from official gov service rather than hardcoded"

---

app/audit/events/RelationshipIdentityVerificationAudit.scala
app/audit/events/ReturningUserIdentityVerificationAudit.scala
app/controllers/reg/ReturningUserController.scala
app/services/MetaDataService.scala
test/controllers/CompletionCapacityControllerSpec.scala
test/controllers/ReturningUserSpec.scala

DL-16185 Explicit Audits for SCRS
